### ISSUE TITLE
New MacBook

### ISSUE THREAD

**Issue by linas1985** [Devbootcamp/phase-0-handbook#35]
I'm considering buying the new MacBook. Will there be any issues with the new ports configuration (essentially it having almost none) while at DBC? Is it something I should avoid buying looking down the line as a programmer?

**Comment by mbtomori** [comment]
@linas1985 Sorry for the delay. There shouldn't be any issues with this while at DBC, and I would guess Apple has designed their computer fairly well for developing, so I doubt it will be a problem in the future in the near term future.
